// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

export const environment = {
  production: true,
  // version: env['npm_package_version'],
leadStatus:'deal',
  version: '1.0.0',
  serverUrl: 'https://akstech.sg/auth/api/v1/',
  apiUrl: 'https://akstech.sg/client/lead/api/',
  authApiUrl: 'https://akstech.sg/auth/api/v1/',
  smiApiUrl: 'https://akstech.sg/client/smi/v1/',
  baseUrl: 'https://akstech.sg/',
  marketingApiUrl: 'https://akstech.sg/3rdparty/bolt/api/',
  apiVersion: 'v1',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
};
