name: Audit

on:
  pull_request:
    branches: [ dev ]
    types: [closed]

jobs:

  # audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker Angular Frontend
      run: docker build -t karthiksgd/crm-client-frontend:v1.0.9 -f ./Dockerfile ./

    - name: Docker Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_ID}}" --password-stdin

    - name: Push Frontend to Docker Hub
      run: |
        docker push karthiksgd/crm-client-frontend:v1.0.9

