name: Audit

on:
  push:
    branches: [dev]

jobs:

  # audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker Angular Frontend
      run: docker build -t karthiksgd/crm-frontend:v1.0.12 -f ./Dockerfile ./

    - name: Docker Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_ID}}" --password-stdin

    - name: Push Frontend to Docker Hub
      run: |
        docker push karthiksgd/crm-frontend:v1.0.12

